### ISSUE TITLE
DW Approval

### ISSUE THREAD

**Issue by jonalf** [VictorTeoh/systems_Project2#1]
You need more detail in your design. What games are you planning on implementing? Do you need to use SDL or will you work in a text based environment? Your general idea is fine, but I need some more information please.

**Comment by jensenli049** [comment]
We plan on implementing all the Potential Games if time permits. Otherwise, we will prioritize Ultimate Tic-tac-toe, Connect 4, Mastermind and Hangman. As recently edited in the Design, all potential games we listed will use SDL except Hangman (text based environment).

**Comment by jonalf** [comment]
This is approved, but you need to get on SDL quickly.
